In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("/content/Bangalore_AQI_Dataset.csv")
data

,City,Date,AQI,PM2.5,PM10,NO2,SO2,CO,O3
0,Bangalore,01/01/18,68,37.40,73.44,56.44,77.52,0.71,64.60
1,Bangalore,02/01/18,76,41.80,82.08,63.08,86.64,0.80,72.20
2,Bangalore,03/01/18,70,38.50,75.60,58.10,79.80,0.74,66.50
3,Bangalore,04/01/18,78,42.90,84.24,64.74,88.92,0.82,74.10
4,Bangalore,05/01/18,82,45.10,88.56,68.06,93.48,0.86,77.90
...,...,...,...,...,...,...,...,...,...
2551,Bangalore,27/12/24,54,29.70,58.32,44.82,61.56,0.57,51.30
2552,Bangalore,28/12/24,57,31.35,61.56,47.31,64.98,0.60,54.15
2553,Bangalore,29/12/24,70,38.50,75.60,58.10,79.80,0.74,66.50
2554,Bangalore,30/12/24,62,34.10,66.96,51.46,70.68,0.65,58.90


In [3]:
data.columns

Index(['City', 'Date', 'AQI', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3'], dtype='object')

In [4]:
data.isna().sum()

,0
City,0
Date,0
AQI,0
PM2.5,0
PM10,0
NO2,0
SO2,0
CO,0
O3,0


In [5]:
data.duplicated().sum()

np.int64(0)

In [6]:
data.sample(3)

,City,Date,AQI,PM2.5,PM10,NO2,SO2,CO,O3
268,Bangalore,26/09/18,81,44.55,87.48,67.23,92.34,0.85,76.95
2083,Bangalore,16/09/23,40,22.00,43.20,33.20,45.60,0.42,38.00
1530,Bangalore,12/03/22,108,59.40,116.64,89.64,123.12,1.13,102.60


In [7]:
data=data.drop(columns=['City','Date'])

In [8]:
data.head(2)

,AQI,PM2.5,PM10,NO2,SO2,CO,O3
0,68,37.4,73.44,56.44,77.52,0.71,64.6
1,76,41.8,82.08,63.08,86.64,0.80,72.2


In [9]:
x=data.drop(columns=['AQI'])
y=data['AQI']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

In [12]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [13]:
model.predict(x_test)

array([100.  ,  43.  ,  60.  ,  54.  ,  77.  ,  93.  ,  54.  , 108.  ,
        85.  ,  88.  ,  74.  ,  53.  , 106.  ,  86.  ,  95.  ,  38.  ,
        39.  ,  71.  , 106.  ,  52.  ,  47.  ,  42.  ,  71.  ,  54.  ,
        57.  ,  71.  , 100.  ,  87.  ,  48.  ,  57.  ,  73.  ,  91.  ,
        61.  , 122.  ,  71.  ,  89.  ,  48.  ,  93.  ,  88.  ,  96.  ,
       104.  ,  67.  ,  76.  ,  48.  , 119.  , 108.  ,  47.  , 125.  ,
        51.  ,  62.  ,  78.  ,  65.  ,  59.  ,  79.  ,  96.  ,  53.  ,
        94.  ,  93.  ,  58.  ,  53.  ,  75.  ,  55.  ,  51.  ,  43.  ,
       111.  , 129.93, 144.  ,  57.  ,  76.  ,  57.  ,  59.  , 112.  ,
        74.  , 122.  ,  40.  ,  38.  ,  74.  ,  60.  , 100.  ,  50.  ,
        95.  ,  94.  ,  69.  ,  66.  , 110.  , 103.  ,  86.  ,  97.  ,
        60.  ,  72.  ,  95.  ,  91.  ,  46.  ,  68.  ,  81.  ,  51.  ,
        79.  ,  44.  ,  74.  , 106.  ,  56.  , 123.95,  61.  ,  40.  ,
        99.  ,  55.  ,  68.  ,  64.  ,  77.  ,  84.  ,  76.  , 101.  ,
      

In [14]:
model.score(x_test,y_test)

0.9999874147178984

In [15]:
model.predict([[31.35,61.56,47.31,64.98,0.60,54.15]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([57.])

In [16]:
model.predict([[37.40,73.44,56.44,77.52,0.71,64.60]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([68.])

In [17]:
import pickle
with open('model.pkl','wb') as files:
  pickle.dump(model,files)